# Generated by Django 5.0.7 on 2024-07-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_user_is_bits'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_laboratory',
            field=models.BooleanField(default=False, verbose_name='Is Laboratory'),
        ),
    ]
