# Generated by Django 5.1 on 2024-08-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_is_laboratory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_Faculty',
        ),
        migrations.AddField(
            model_name='user',
            name='is_multimedia',
            field=models.BooleanField(default=False, verbose_name='Is Multimedia'),
        ),
    ]
