# Generated by Django 5.1 on 2024-09-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_user_is_faculty_user_is_multimedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_laboratory',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_multimedia',
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.BooleanField(default=False, verbose_name='Faculty'),
        ),
    ]
