# Generated by Django 5.1.1 on 2024-09-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_it_chairman_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='it_chairman',
        ),
    ]
