# Generated by Django 5.1.1 on 2024-09-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_user_it_chairman'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='it_chairman',
            field=models.BooleanField(default=False, verbose_name='IT Chairman'),
        ),
    ]
