# Generated by Django 5.1.1 on 2024-09-24 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_user_it_chairman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='it_chairman',
        ),
    ]
