# Generated by Django 5.1.1 on 2024-09-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_borrowrequest_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
