# Generated by Django 5.1.1 on 2024-09-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_alter_borrowrequest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='borrower_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
