# Generated by Django 5.1.1 on 2024-09-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_borrowrequest_borrower_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyitem',
            name='property_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facultyitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
