# Generated by Django 5.1.1 on 2024-09-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_facultyitem_property_id_alter_facultyitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyitem',
            name='property_id',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
    ]
