# Generated by Django 5.1.1 on 2024-10-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_borrowrequest_handled_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
