# Generated by Django 5.1.1 on 2024-10-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0008_alter_borrowrequest_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
