# Generated by Django 5.1.1 on 2024-10-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0009_alter_borrowrequest_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
