# Generated by Django 5.1.1 on 2024-10-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0010_borrowrequest_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowrequest',
            old_name='profile_picture',
            new_name='upload_image',
        ),
    ]
