# Generated by Django 5.1.1 on 2024-10-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0011_rename_profile_picture_borrowrequest_upload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='upload_image',
            field=models.ImageField(blank=True, null=True, upload_to='borrow_upload/'),
        ),
    ]
