# Generated by Django 5.1.1 on 2024-10-30 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0012_alter_borrowrequest_upload_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('borrow_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='faculty.borrowrequest')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.facultyitem')),
            ],
        ),
    ]
