# Generated by Django 5.1.1 on 2024-10-31 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0013_borrowrequestitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowrequestitem',
            old_name='quantity',
            new_name='quantityy',
        ),
    ]
