# Generated by Django 5.1.1 on 2024-10-31 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0014_rename_quantity_borrowrequestitem_quantityy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrequest',
            name='quantity',
        ),
    ]
