# Generated by Django 5.1.1 on 2024-11-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0015_remove_borrowrequest_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequestitem',
            name='date_return',
            field=models.DateField(blank=True, null=True),
        ),
    ]
