# Generated by Django 5.1.1 on 2024-11-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0016_borrowrequestitem_date_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequestitem',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
