# Generated by Django 5.1.1 on 2024-11-04 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0017_borrowrequestitem_is_returned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrequest',
            name='handled_by',
        ),
        migrations.AddField(
            model_name='borrowrequestitem',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handled_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
