# Generated by Django 5.1.1 on 2024-11-04 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0018_remove_borrowrequest_handled_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='facultyitem',
            name='quantity',
        ),
    ]
