# Generated by Django 5.1.1 on 2024-11-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0019_remove_facultyitem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyitem',
            name='property_id',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
