# Generated by Django 5.1.1 on 2024-11-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0020_alter_facultyitem_property_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrequestitem',
            name='quantityy',
        ),
    ]
