# Generated by Django 5.1.1 on 2024-11-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0021_remove_borrowrequestitem_quantityy'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
