# Generated by Django 5.1.1 on 2024-11-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0022_borrowrequest_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrequest',
            name='description',
        ),
        migrations.AddField(
            model_name='borrowrequestitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
