# Generated by Django 5.1.1 on 2024-11-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0023_remove_borrowrequest_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequestitem',
            name='quantityy',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
