# Generated by Django 5.1.1 on 2024-11-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0024_borrowrequestitem_quantityy'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
