# Generated by Django 5.1.1 on 2024-11-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0025_facultyitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
