# Generated by Django 5.1.1 on 2024-11-07 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0026_alter_borrowrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRequestItemFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_return', models.DateField(blank=True, null=True)),
                ('quantityy', models.PositiveIntegerField()),
                ('is_returned', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('borrow_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facultyitems', to='faculty.borrowrequest')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handled_faculty_items', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.facultyitem')),
            ],
        ),
    ]
