# Generated by Django 5.1.1 on 2024-11-09 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0027_borrowrequestitemfaculty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorrowRequestItem',
        ),
    ]
