# Generated by Django 5.1.1 on 2024-11-15 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('faculty', '0028_delete_borrowrequestitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
