# Generated by Django 5.1.1 on 2024-11-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0029_alter_borrowrequest_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequestitemfaculty',
            name='item_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
