# Generated by Django 5.1.1 on 2024-11-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0030_borrowrequestitemfaculty_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyitem',
            name='total_quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
