# Generated by Django 5.1.1 on 2024-11-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0031_facultyitem_total_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyitem',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
