# Generated by Django 5.1.1 on 2024-11-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0032_alter_facultyitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='course',
            field=models.CharField(choices=[('BS INFORMATION TECHNOLOGY', 'BS INFORMATION TECHNOLOGY'), ('BS INDUSTRIAL TECHNOLOGY', 'BS INDUSTRIAL TECHNOLOGY'), ('BS ELECTRICAL ENGINEERING', 'BS ELECTRICAL ENGINEERING'), ('BS MECHANICAL ENGINEERING', 'BS MECHANICAL ENGINEERING')], max_length=100),
        ),
    ]
