# Generated by Django 5.1.1 on 2024-12-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0033_alter_borrowrequest_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyitem',
            name='property_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
