# Generated by Django 5.1.1 on 2024-12-18 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0034_alter_facultyitem_property_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(blank=True, max_length=100)),
                ('faculty_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_ids', to='faculty.facultyitem')),
            ],
        ),
    ]
