# Generated by Django 5.1.1 on 2024-12-18 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0035_propertyid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyitem',
            name='property_id',
        ),
    ]
