# Generated by Django 5.1.1 on 2024-12-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0036_remove_facultyitem_property_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyitem',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
