# Generated by Django 5.1.1 on 2024-12-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0037_facultyitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyitem',
            name='status',
        ),
        migrations.AddField(
            model_name='propertyid',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
