# Generated by Django 5.1.4 on 2024-12-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0040_rename_sent_at_emailreminderlog_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailreminderlog',
            name='notification_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
