# Generated by Django 5.1.4 on 2024-12-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0041_emailreminderlog_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailreminderlog',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
