# Generated by Django 5.1 on 2024-09-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservationuser_year_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationuser',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
