# Generated by Django 5.1 on 2024-09-06 23:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservationuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationuser',
            name='student_id',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
