# Generated by Django 5.1 on 2024-09-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_reservationuser_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
