# Generated by Django 5.1 on 2024-09-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_reservationuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationuser',
            name='profile_image',
            field=models.ImageField(default='users.jpg', upload_to='profile_pics/'),
        ),
    ]
