# Generated by Django 5.1 on 2024-09-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_reservationuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationuser',
            name='profile_image',
            field=models.ImageField(default='profile_pics/users.jpg', upload_to='profile_pics/'),
        ),
    ]
