# Generated by Django 5.1 on 2024-09-13 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_alter_reservationuser_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationuser',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='reservationuser',
            name='last_name',
        ),
    ]
