# Generated by Django 5.1 on 2024-09-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_rename_first_name_reservationuser_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationuser',
            name='course',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
