# Generated by Django 5.1 on 2024-09-13 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
