# Generated by Django 5.1 on 2024-09-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0014_studentreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreservation',
            name='borrow_date',
            field=models.CharField(max_length=40),
        ),
    ]
