# Generated by Django 5.1 on 2024-09-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0015_alter_studentreservation_borrow_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreservation',
            name='is_laboratory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentreservation',
            name='is_multimedia',
            field=models.BooleanField(default=False),
        ),
    ]
