# Generated by Django 5.1 on 2024-09-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0016_studentreservation_is_laboratory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreservation',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
