# Generated by Django 5.1 on 2024-09-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0017_studentreservation_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentreservation',
            old_name='borrow_date',
            new_name='reserve_date',
        ),
    ]
