# Generated by Django 5.1 on 2024-09-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0018_rename_borrow_date_studentreservation_reserve_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreservation',
            name='year_level',
            field=models.CharField(max_length=50),
        ),
    ]
