# Generated by Django 5.1 on 2024-09-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0019_alter_studentreservation_year_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreservation',
            name='notification',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
