# Generated by Django 5.1 on 2024-09-17 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0020_studentreservation_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentreservation',
            name='user_id',
        ),
        migrations.AddField(
            model_name='studentreservation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservation.reservationuser'),
            preserve_default=False,
        ),
    ]
