# Generated by Django 5.1 on 2024-09-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0021_remove_studentreservation_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationuser',
            name='confirm_password',
        ),
    ]
