# Generated by Django 5.1 on 2024-09-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0022_remove_reservationuser_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreservation',
            name='handled_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
