# Generated by Django 5.1 on 2024-09-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0023_studentreservation_handled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreservation',
            name='handled_by_profile_picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
