# Generated by Django 5.1 on 2024-09-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0024_studentreservation_handled_by_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreservation',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
