# Generated by Django 5.1 on 2024-09-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0025_studentreservation_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreservation',
            name='is_handled',
            field=models.BooleanField(default=False),
        ),
    ]
