# Generated by Django 5.1 on 2024-09-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0026_studentreservation_is_handled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentreservation',
            name='is_laboratory',
        ),
        migrations.RemoveField(
            model_name='studentreservation',
            name='is_multimedia',
        ),
    ]
