# Generated by Django 5.1 on 2024-09-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0027_remove_studentreservation_is_laboratory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreservation',
            name='user_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
