# Generated by Django 5.1 on 2024-09-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0028_studentreservation_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreservation',
            name='reserve_date',
            field=models.DateField(),
        ),
    ]
