# Generated by Django 5.1.1 on 2024-09-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0029_alter_studentreservation_reserve_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationuser',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservationuser',
            name='student_id',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
