# Generated by Django 5.1.1 on 2024-09-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0030_reservationuser_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
