# Generated by Django 5.1.1 on 2024-09-29 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0033_alter_reservationuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationuser',
            name='last_login',
        ),
    ]
