# Generated by Django 5.1.1 on 2024-11-05 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0035_remove_studentreservation_quantity_reservationitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentreservation',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='studentreservation',
            name='object_id',
        ),
    ]
