# Generated by Django 5.1.1 on 2024-11-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0036_remove_studentreservation_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreservation',
            name='reserve_date',
            field=models.CharField(max_length=50),
        ),
    ]
