# Generated by Django 5.1.1 on 2024-11-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0038_alter_studentreservation_reserve_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreservation',
            name='purpose',
            field=models.TextField(null=True),
        ),
    ]
