# Generated by Django 5.1.1 on 2024-11-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0039_alter_studentreservation_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreservation',
            name='reserve_date',
            field=models.CharField(max_length=50),
        ),
    ]
