# Generated by Django 5.1.1 on 2024-11-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0040_alter_studentreservation_reserve_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationitem',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
