# Generated by Django 5.1.1 on 2024-11-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0041_reservationitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationitem',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
