# Generated by Django 5.1.1 on 2024-11-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0043_remove_studentreservation_handled_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreservation',
            name='handled_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentreservation',
            name='handled_by_profile_picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='studentreservation',
            name='is_handled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentreservation',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentreservation',
            name='notification',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='studentreservation',
            name='user_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
