# Generated by Django 5.1.1 on 2024-11-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0044_studentreservation_handled_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationitem',
            name='is_update',
            field=models.BooleanField(default=False),
        ),
    ]
