# Generated by Django 5.1.1 on 2024-11-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0045_reservationitem_is_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
