# Generated by Django 5.1.1 on 2024-11-09 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0046_reservationitem_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentreservation',
            name='handled_by',
        ),
        migrations.RemoveField(
            model_name='studentreservation',
            name='handled_by_profile_picture',
        ),
        migrations.RemoveField(
            model_name='studentreservation',
            name='is_handled',
        ),
        migrations.RemoveField(
            model_name='studentreservation',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='studentreservation',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='studentreservation',
            name='user_type',
        ),
    ]
