# Generated by Django 5.1.1 on 2024-11-09 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0049_alter_studentreservation_user_facultyitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reservation.reservationuser'),
            preserve_default=False,
        ),
    ]
