# Generated by Django 5.1.1 on 2024-11-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0051_remove_studentreservation_user_facultyitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
