# Generated by Django 5.1.1 on 2024-11-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0052_studentreservation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreservation',
            name='handle_status',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
