# Generated by Django 5.1.1 on 2024-11-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0053_studentreservation_handle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreservation',
            name='handle_status',
            field=models.CharField(default='Pending', max_length=15),
        ),
    ]
