# Generated by Django 5.1.1 on 2024-11-11 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0054_alter_studentreservation_handle_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentreservation',
            name='handle_status',
        ),
        migrations.CreateModel(
            name='HandleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle_status', models.CharField(default='Pending', max_length=15)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handle_status', to='reservation.studentreservation')),
            ],
        ),
    ]
