# Generated by Django 5.1.1 on 2024-11-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0055_remove_studentreservation_handle_status_handlestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreservation',
            name='handle_status',
            field=models.CharField(default='Pending', max_length=15),
        ),
        migrations.DeleteModel(
            name='HandleStatus',
        ),
    ]
