# Generated by Django 5.1.1 on 2024-11-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0056_studentreservation_handle_status_delete_handlestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentreservation',
            name='handle_status',
        ),
        migrations.AddField(
            model_name='reservationitem',
            name='handle_status',
            field=models.CharField(default='Pending', max_length=15),
        ),
    ]
