# Generated by Django 5.1.1 on 2024-11-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0057_remove_studentreservation_handle_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationitem',
            name='description',
            field=models.TextField(default='N/A'),
        ),
    ]
