# Generated by Django 5.1.1 on 2024-11-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0058_alter_reservationitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreservation',
            name='date_return',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
