# Generated by Django 5.1.1 on 2024-11-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0059_studentreservation_date_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreservation',
            name='upload_image',
            field=models.ImageField(blank=True, null=True, upload_to='borrow_upload/'),
        ),
    ]
