# Generated by Django 5.1.1 on 2024-12-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0060_studentreservation_upload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreservation',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
