# Generated by Django 5.1.1 on 2024-12-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0061_alter_studentreservation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
